---
apiVersion: v1
kind: Namespace
metadata:
  name: check-mk
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: check-mk
  namespace: check-mk
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: check-mk
rules:
<<<<<<< HEAD
- apiGroups: [""]
=======
- apiGroups:
  - ""
  - storage.k8s.io
  - rbac.authorization.k8s.io
  - apps
  - extensions
  - batch
  - autoscaling
  - networking.k8s.io/v1beta1
>>>>>>> upstream/master
  resources:
  - componentstatuses
  - nodes
  - nodes/proxy
  - services
  - pods
  - configmaps
  - secrets
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  - persistentvolumes
  - namespaces
  - endpoints
<<<<<<< HEAD
  verbs: ["get", "list"]
- apiGroups: ["storage.k8s.io"]
  resources:
  - storageclasses
  verbs: ["get", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  - clusterroles
  - roles
  verbs: ["get", "list"]
- apiGroups: ["extensions"]
  resources:
=======
  - storageclasses
  - clusterroles
  - roles
>>>>>>> upstream/master
  - daemonsets
  - deployments
  - replicasets
  - ingresses
<<<<<<< HEAD
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources:
  - cronjobs
  - jobs
  verbs: ["get", "list"]
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs: ["list", "watch"]
=======
  - statefulsets
  - cronjobs
  - jobs
  - horizontalpodautoscalers
  verbs: ["get", "list"]
>>>>>>> upstream/master
- apiGroups:
  - custom.metrics.k8s.io
  resources: ["*"]
  verbs:
  - get
  - list
- nonResourceURLs:
  - /version
  - /healthz
  - /metrics
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: check-mk
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: check-mk
subjects:
- kind: ServiceAccount
  name: check-mk
  namespace: check-mk
